name: Build-CI-Develop

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      run: npm i

    - name: Lint packages
      run: npm run lint -- --since origin/main

    - name: Test packages
      run: npm run test -- --since origin/main

    - name: Build packages
      run: npm run build -- --since origin/main

      env:
        CI: true
