name: Build-CI-Others

on:
  push:
    branches:
      - '*'           # matches every branch that doesn't contain a '/'
      - '*/*'         # matches every branch containing a single '/'
      - '**'          # matches every branch
      - '!main'       # excludes main
      - '!develop'       # excludes develop
      - '!release/*'  # excludes release
      - '!snapshot'   # excludes snapshot

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm i

    - name: Lint packages
      run: npm run lint -- --since origin/develop

    - name: Test packages
      run: npm run test -- --since origin/develop

    - name: Build packages
      run: npm run build -- --since origin/develop

      env:
        CI: true
