name: Build-CI-Release

on:
  push:
    branches:
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm i

    - name: Lint packages
      run: npm run lint

    - name: Test packages
      run: npm run test

    - name: Build packages
      run: npm run build

    - name: Version packages
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npx changeset version
        git add .
        git commit -m "chore: release packages" --no-verify
        git push --no-verify

      env:
        CI: true
